FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run", "dev"]




