FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy application files
COPY . .

# Generate Prisma Client
RUN npx prisma generate

EXPOSE 3001

ENV PORT 3001
ENV NODE_ENV development

CMD ["npm", "run", "start:dev"]




